// Tire tuning and physics calculation module for Gran Turismo 7 downforce optimization
// This module contains the core physics algorithms used to calculate grip, downforce, and suspension frequency

// Maps tire compound codes to grip coefficients used in downforce/frequency calculations
// Higher grip values = more downforce and higher natural frequencies
// Comfort tires (0.82-0.99) provide less grip; Racing tires (1.25-1.33) provide max grip
export const gripDict = {
  ch: 0.82, cm: 0.90, cs: 0.99,  // Comfort: Hard, Medium, Soft (lowest grip)
  sh: 1.05, sm: 1.09, ss: 1.16,  // Sports: Hard, Medium, Soft (mid grip)
  rh: 1.25, rm: 1.29, rs: 1.33,  // Racing: Hard, Medium, Soft (highest grip)
};

// Human-readable tire names displayed in response embeds
// Maps uppercase tire codes to marketing names shown to Discord users
export const tireNames = {
  CH: 'Comfort Hard',   CM: 'Comfort Medium', CS: 'Comfort Soft',
  SH: 'Sports Hard',    SM: 'Sports Medium',  SS: 'Sports Soft',
  RH: 'Racing Hard',    RM: 'Racing Medium',  RS: 'Racing Soft',
};

// Type definitions for function results (JSDoc for IDE support)
// SuccessResult: returns calculated tuning values formatted for display
// ErrorResult: returns error message if calculation fails
// TuneResult: union type that can be either success or error
/**
 * @typedef {{ frontDF: string, rearDF: string, frontNF: string, rearNF: string, grip: string, tireDisplay: string }} SuccessResult
 * @typedef {{ error: string }} ErrorResult
 * @typedef {SuccessResult | ErrorResult} TuneResult
 */

/**
 * Core physics calculation function for GT7 grip-optimized tuning
 * Calculates downforce (in lbs) and natural frequency (Hz) for suspension setup
 * @param {number} weightLbs - Total car weight in pounds (1000-5000 lbs)
 * @param {number} frontPercent - Front weight distribution percentage (30-70%)
 * @param {string} tire - Tire compound code (e.g., 'ch', 'rh', 'ss')
 * @returns {TuneResult} - Object with downforce/frequency values or error message
 */
export function calculateGripTune(weightLbs, frontPercent, tire) {
  // Normalize tire input to lowercase and look up grip coefficient
  const tireKey = tire.toLowerCase();
  const grip = gripDict[tireKey] ?? 1.0;  // Default to neutral grip if not found

  // Validate front weight distribution is within safe tuning range
  // Extreme distributions (< 30% or > 70%) indicate unrealistic setups
  if (frontPercent < 30 || frontPercent > 70) {
    return { error: 'Front weight % must be between 30 and 70.' };
  }

  // Calculate weight distribution ratios from front percentage
  // Example: 54% front = 0.54 front ratio, 0.46 rear ratio
  const frontRatio = frontPercent / 100;
  const rearRatio = 1 - frontRatio;

  // Distribute total weight between front and rear axles based on percentage
  const frontWeight = weightLbs * frontRatio;  // Front axle load
  const rearWeight = weightLbs * rearRatio;     // Rear axle load

  // Calculate natural frequencies (Hz) for suspension tuning
  // Lower frequency = softer suspension (more comfort, slower response)
  // Higher frequency = stiffer suspension (more responsive, rougher ride)
  // baseNF scaled by grip; higher grip = higher ideal frequency
  const baseNF = grip * 2.0;                      // Grip-adjusted base frequency
  const frontNF = Math.max(1.40, Math.min(3.30, baseNF * 1.06));  // 1.06x for front stability (clamped 1.40-3.30)
  const rearNF = Math.max(1.40, Math.min(3.30, baseNF * 0.94));   // 0.94x for rear control (clamped 1.40-3.30)

  // Calculate downforce generated by each axle (in pounds force)
  // Downforce = weight * grip * conversion factor
  // Higher downforce increases grip but adds drag; balanced tuning required
  const dfPerLb = 0.11;  // 0.11 lbs of downforce per lb of car weight
  const frontDF = Math.max(0, Math.min(300, frontWeight * grip * dfPerLb));  // Constrained 0-300 lbs
  const rearDF = Math.max(0, Math.min(300, rearWeight * grip * dfPerLb));    // Constrained 0-300 lbs

  // Return calculation results formatted for Discord embed display
  return {
    frontDF:  frontDF.toFixed(1),                                      // Front downforce (1 decimal)
    rearDF:   rearDF.toFixed(1),                                       // Rear downforce (1 decimal)
    frontNF:  frontNF.toFixed(2),                                      // Front frequency Hz (2 decimals)
    rearNF:   rearNF.toFixed(2),                                       // Rear frequency Hz (2 decimals)
    grip:     grip.toFixed(2),                                         // Grip coefficient (2 decimals)
    tireDisplay: tireNames[tire.toUpperCase()] || tire.toUpperCase(),  // Human-readable tire name
  };
}

